apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: Some description for project ${{ values.name | dump }} could come here.
  annotations:
    backstage.io/techdocs-reg: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
